<?php
/**
 * Auto-Generated by PhpStorm.
 * User: Junaid Shakoor
 * Date: 07-Nov-16
 */
session_start();

ini_set("display_errors", true);
date_default_timezone_get("Europe/London");
define("DB_SERVERNAME","devweb2016.cis.strath.ac.uk");
define("DB_USERNAME", "cs312j");
define("DB_PASSWORD", "ooV3oopheeMi");
define("DB_NAME", "cs312j");
define("ADMIN_USERNAME", "admin");
define("ADMIN_PASSWORD", "admin");

require "article.php";

// main exception handler if we do something horribly wrong
function handleException($exception){
    echo "Error: ".$exception->getMessage();
}
set_exception_handler('handleException');

?>
